version: '3'
services:
  app:
    container_name: node_app
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
